nginx:
  image: dockerfile/nginx
  ports:
    - "80:80"
  volumes:
    - ~/ifjs/nginx_config:/etc/nginx:ro
  links:
    - ghost

ghost:
  image: dockerfile/ghost
  ports:
    - "2368:2368"
  volumes:
    - ~/ifjs/ghost_config:/ghost-override