nginx:
  image: dockerfile/nginx
  ports:
    - "80:80"
  volumes:
    - ~/nginx_config:/etc/nginx:ro
  links:
    - ghost:ghost

ghost:
  image: dockerfile/ghost
  ports:
    - "2368:2368"
  volumes:
    - ~/ghost_config:/ghost-override